imports:
    - php
    - javascript

filter:
    paths: ["app/*"]
    excluded_paths: ["/vendor/*", "/build/*", "/database/*", "/test/*"]

checks:
    php: true
    javascript: true

build:
    nodes:
        analysis:
            environment:
                php:
                    version: 8.0

    tests:
        before:
            - cd app/
        override:
            - true
                  - command: make test
                  - coverage:
                        file: build/coverage.clover
                        format: clover