imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*]

build:
    nodes:
        my-tests:
            environment:
                php:
                    version: 8.0
    tests:
        override:
            - cd app/
                command: "make test"
                coverage:
                    file: "build/coverage.clover"
                    format: "php-clover"
