imports:
    - php
    - javascript

filter:
    paths: ["app/app/Http/Controllers/*", "app/app/Models/*", "app/app/Dice/*","app/app/Yatzy/*", "app/app/Traits/*", "app/routes/web.php"]
    excluded_paths: ["app/vendor/*", "app/build/*", "app/database/*", "app/tests/*"]

checks:
    php: true
    javascript: true

build:
    nodes:
        analysis:
            environment:
                php:
                    version: 8.0

    tests:
        before:
            - cd app/
        override:
            - true
                - command: make test
                - coverage:
                      file: build/coverage.clover
                      format: clover