imports:
    - php

filter:
    paths: [app/app/Dice/*,
            app/app/Models/*,
            app/app/Traits/*,
            app/app/Yatzy/*,
            app/app/Http/Controllers/*,
            app/routes/web.php]

    excluded_paths: [app/database/*,
                     app/tests/*]

    dependency_paths: [app/build/*,
                       app/vendor/*]

checks:
    php: true

build:
    nodes:
        analysis:
            project_setup:
                override:
                    - true
            tests:
                override:
                    - php-scrutinizer-run --enable-security-analysis
            environment:
                php:
                    version: 8.0

    tests:
        before:
            - cd app/
        override:
            - true
                  - command: make install test
                  coverage:
                      file: build/coverage.clover
                      format: php-clover
