<?php

declare(strict_types=1);


/**
 * Namespace declared and others in use.
 */
namespace Daap19\UnitTests;
use App\Http\Controllers\LibraryController;
use Tests\TestCase;



/**
 * Test suite for the controller.
 */
class LibraryControllerTest extends TestCase
{
    protected object $libraryController;

    /**
     * @description setUp for test suit. Each test case will run this at first.
     */
    final protected function setUp(): void
    {
        $this->libraryController = new LibraryController();
    }


    /**
     * @description tearDown for test suit. Each test case will run this when done is done.
     */
    final protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }


    /**
     * @test Test for methods existance on the controller object.
     * @description
     */
    final public function test_LibraryController(): void
    {
        $this->assertIsObject($this->libraryController);
        $this->assertInstanceOf('App\Http\Controllers\LibraryController', $this->libraryController);
        $this->assertInstanceOf(LibraryController::class, $this->libraryController);

        $this->assertTrue(method_exists($this->libraryController, 'viewLibrary'));
        $this->assertTrue(method_exists($this->libraryController, 'viewBook'));
        $this->assertTrue(method_exists($this->libraryController, 'viewCategory'));
        $this->assertTrue(method_exists($this->libraryController, 'viewAuthor'));
        $this->assertTrue(method_exists($this->libraryController, 'viewPublisher'));
    }
}
