<?php

declare(strict_types=1);


/**
 * Namespace declared and others in use.
 */
namespace Daap19\UnitTests;
use App\Http\Controllers\YatzyController;
use Tests\TestCase;



/**
 * Test suite for the controller.
 */
class YatzyControllerTest extends TestCase
{
    protected object $yatzyController;

    /**
     * @description setUp for test suit. Each test case will run this at first.
     */
    final protected function setUp(): void
    {
        $this->yatzyController = new YatzyController();
    }


    /**
     * @description tearDown for test suit. Each test case will run this when done is done.
     */
    final protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }


    /**
     * @test
     * @description
     */
    final public function test_YatzyController(): void
    {
        $this->assertIsObject($this->yatzyController);
        $this->assertInstanceOf('App\Http\Controllers\YatzyController', $this->yatzyController);
        $this->assertInstanceOf(YatzyController::class, $this->yatzyController);

        $this->assertTrue(method_exists($this->yatzyController, 'viewInit'));
        $this->assertTrue(method_exists($this->yatzyController, 'processInit'));
        $this->assertTrue(method_exists($this->yatzyController, 'viewMain'));
        $this->assertTrue(method_exists($this->yatzyController, 'processMain'));
        $this->assertTrue(method_exists($this->yatzyController, 'viewSelect'));
        $this->assertTrue(method_exists($this->yatzyController, 'processSelect'));
        $this->assertTrue(method_exists($this->yatzyController, 'viewResult'));
        $this->assertTrue(method_exists($this->yatzyController, 'processResult'));
        $this->assertTrue(method_exists($this->yatzyController, 'viewHighscore'));
    }
}
